name: test
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Configure Action Environment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with: 
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main'
            ]
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
